#!/usr/bin/env python
"""Generate the teaching notebooks from their builders, and audit their shape.

    python tools/build_notebooks/build.py --check          # audit only
    python tools/build_notebooks/build.py 04d              # write one
    python tools/build_notebooks/build.py --all            # write all

`CLAUDE.md` Part 4's corollary: if a notebook is generated by a script, the
script is the source of truth and the notebook is a build output, and something
must check that regenerating reproduces what shipped —
`tests/test_notebook_sources.py` is that check.

**Writing a notebook here discards its outputs.** That is the whole reason the
regeneration test compares *sources* only: a shipped notebook carries outputs a
regeneration cannot know. So the workflow is: edit the builder, `--all`, execute
the notebooks, commit them executed. Never hand-edit a notebook's cells — the
next `--all` would silently throw the edit away.

`--check` reports the Part 10 pre-ship measurements without writing anything:
where the first long function sits, how long the longest teaching cell is, how
many code cells have no markdown above them, how many predict-prompts there are.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import sys
from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))

# A teaching cell may hold a function only if the function IS the lesson (an
# algorithm you cannot write out inline, or machinery whose sameness is the
# point). Marking it costs a stated reason and a column in the audit table.
LESSON_MARK = "THE FUNCTION IS THE LESSON"

# every notebook the builders can produce, in series order
BUILDERS = {
    "01": "build_notebooks.nb_01",
    "02": "build_notebooks.nb_02",
    "02b": "build_notebooks.nb_02b",
    "02c": "build_notebooks.nb_02c",
    "04ab": "build_notebooks.nb_04ab",
    "04c": "build_notebooks.nb_04c",
    "04c_exact": "build_notebooks.nb_04c_exact",
    "04d": "build_notebooks.nb_04d",
    "04e": "build_notebooks.nb_04e",
}

# what the shipped kernel actually ran; keep this matching reality (rule 3)
KERNEL = {
    "kernelspec": {"display_name": "Python 3", "language": "python",
                   "name": "python3"},
    "language_info": {"name": "python", "version": "3.13.9"},
}


def load(tag: str):
    if tag not in BUILDERS:
        raise SystemExit(f"unknown notebook {tag!r}; choose from {sorted(BUILDERS)}")
    try:
        return importlib.import_module(BUILDERS[tag])
    except ModuleNotFoundError as exc:
        if BUILDERS[tag].split(".")[-1] in str(exc):
            raise SystemExit(
                f"{tag} is listed in BUILDERS but {BUILDERS[tag]} does not exist "
                f"yet. Remove it from BUILDERS or write the builder."
            ) from exc
        raise


def notebook(tag: str) -> nbf.NotebookNode:
    """Build one notebook, without outputs."""
    mod = load(tag)
    nb = nbf.v4.new_notebook()
    nb.cells = [nbf.v4.new_markdown_cell(t) if kind == "md"
                else nbf.v4.new_code_cell(t)
                for kind, t in mod.cells()]
    nb.metadata = dict(KERNEL)
    return nb


# The shared structure cell is identifiable by the comment on its horizon knob.
# Every name it binds is a knob later cells read; none of them is a name a later
# cell should rebind. See _knob_shadowing below.
STRUCTURE_CELL_MARK = "# horizon, years"


def _assigned_names(src: str) -> set:
    """Names bound in one cell's MODULE scope.

    Descends into `for` / `while` / `if` / `with` / `try` bodies, because a
    binding there leaks to module scope and that is exactly where the bug this
    check exists for lived. Does NOT descend into function or class bodies, and
    ignores comprehension targets, since neither leaks.
    """
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return set()
    out, stack = set(), list(tree.body)
    while stack:
        node = stack.pop()
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.add(node.name)                  # the def itself binds a name
            continue                            # but its body is another scope
        targets = []
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, (ast.For, ast.AsyncFor, ast.AugAssign, ast.AnnAssign)):
            targets = [node.target]
        for t in targets:
            for x in ast.walk(t):
                if isinstance(x, ast.Name):
                    out.add(x.id)
        for field in ("body", "orelse", "finalbody", "handlers"):
            stack.extend(getattr(node, field, []) or [])
    return out


def _knob_shadowing(cells) -> list:
    """Names the shared structure cell defines that a later cell rebinds."""
    code = [(i, t) for i, (k, t) in enumerate(cells) if k == "code"]
    struct = next((i for i, t in code if STRUCTURE_CELL_MARK in t), None)
    if struct is None:
        return []
    knobs = _assigned_names(dict(code)[struct])
    clashes = []
    for i, t in code:
        if i <= struct or "CARRIED OVER" in t:
            continue                            # carried cells re-declare knobs
        for name in sorted(_assigned_names(t) & knobs):
            clashes.append((name, i))
    return clashes


def audit(tag: str, cells) -> dict:
    """The Part 10 pre-ship measurements, as numbers rather than impressions."""
    wrap = next((i for i, (k, t) in enumerate(cells)
                 if k == "md" and "Now the streamlined version" in t), len(cells))
    code_before_wrap = [(i, t) for i, (k, t) in enumerate(cells[:wrap])
                        if k == "code"]
    # A cell marked CARRIED OVER is material another notebook narrates. It is not
    # this notebook's teaching, so it is exempt from the def and cell-length
    # rules -- but it is counted, so the exemption cannot be used quietly.
    carried = [(i, t) for i, t in code_before_wrap if "CARRIED OVER" in t]
    # Part 0's five small functions each ARE the lesson, and CLAUDE.md Part 11
    # blesses that shape. A cell may claim the same exemption, but it must say
    # WHY on the marker line, and it is counted in its own column -- so, like
    # CARRIED OVER, the exemption cannot be taken quietly.
    is_lesson = [(i, t) for i, t in code_before_wrap
                 if LESSON_MARK in t and "CARRIED OVER" not in t]
    for i, t in is_lesson:
        line = next(l for l in t.splitlines() if LESSON_MARK in l)
        if len(line.split(LESSON_MARK, 1)[1].strip(": ")) < 20:
            raise SystemExit(
                f"{tag} cell {i}: {LESSON_MARK} needs a reason after it, "
                f"stating why this function is the lesson rather than an "
                f"abstraction hiding it. Got: {line.strip()!r}")
    exempt = {i for i, _ in carried} | {i for i, _ in is_lesson}
    teaching = [(i, t) for i, t in code_before_wrap if i not in exempt]
    early_defs = [(i, l) for i, t in teaching
                  for l in t.splitlines() if l.startswith("def ")]
    return dict(
        notebook=tag,
        cells=len(cells),
        markdown=sum(1 for k, _ in cells if k == "md"),
        wrap_at=f"{100 * wrap / len(cells):.0f}%",
        carried_over=len(carried),
        fn_is_lesson=len(is_lesson),
        defs_in_teaching=len(early_defs),
        longest_teaching_cell=max((len(t.splitlines()) for _, t in teaching),
                                  default=0),
        orphan_code_cells=sum(1 for i, (k, _) in enumerate(cells)
                              if k == "code"
                              and (i == 0 or cells[i - 1][0] != "md")),
        predict_prompts=sum(1 for k, t in cells
                            if k == "md" and "Predict before you run" in t),
        agreement_assert=any(k == "code" and "disagree" in t and "assert" in t
                             for k, t in cells),
        blank_markers=sum(1 for _, t in cells if "YOUR CODE HERE" in t),
        knob_shadowing=len(_knob_shadowing(cells)),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("which", nargs="*", help=f"any of {sorted(BUILDERS)}")
    ap.add_argument("--all", action="store_true", help="build every notebook")
    ap.add_argument("--check", action="store_true",
                    help="audit only; write nothing")
    args = ap.parse_args()

    tags = sorted(BUILDERS) if args.all else args.which
    if not tags:
        tags = sorted(BUILDERS)
        args.check = True

    rows, failed = [], []
    for tag in tags:
        mod = load(tag)
        cells = mod.cells()
        row = audit(tag, cells)
        rows.append(row)
        if row["defs_in_teaching"]:
            failed.append(f"{tag}: {row['defs_in_teaching']} unmarked function "
                          f"definition(s) in the teaching section")
        if not row["agreement_assert"]:
            failed.append(f"{tag}: no agreement assertion")
        if row["orphan_code_cells"]:
            failed.append(f"{tag}: {row['orphan_code_cells']} code cell(s) with "
                          f"no markdown above")
        if not row["predict_prompts"]:
            failed.append(f"{tag}: no predict-before-you-run prompt")
        if row["blank_markers"]:
            failed.append(f"{tag}: {row['blank_markers']} fill-in-the-blank marker(s)")

        if not args.check:
            out = ROOT / "notebooks" / mod.NOTEBOOK
            nb = notebook(tag)
            out.parent.mkdir(parents=True, exist_ok=True)
            nbf.write(nb, out)
            print(f"wrote {out.relative_to(ROOT)} ({len(nb.cells)} cells, "
                  f"no outputs - execute it before committing)")

    keys = ["notebook", "cells", "markdown", "wrap_at", "carried_over",
            "fn_is_lesson", "knob_shadowing",
            "defs_in_teaching",
            "longest_teaching_cell", "orphan_code_cells", "predict_prompts",
            "agreement_assert", "blank_markers"]
    width = {k: max(len(k), *(len(str(r[k])) for r in rows)) for k in keys}
    print()
    print("  ".join(k.ljust(width[k]) for k in keys))
    for r in rows:
        print("  ".join(str(r[k]).ljust(width[k]) for k in keys))

    if failed:
        print("\nFAILED:")
        for f in failed:
            print(f"  {f}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
